# Exemplo de criação de volume local
# 12/07-2019 - DSS

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: task-pv-volume
  labels: 
    type: local
spec: 
  capacity: 
    storage: 2Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/"

