apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels: 
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: guestbook 
    tier: frontend
  externalIPs:
  - 172.22.6.153
