apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-slave
spec:
  replicas: 2
  template: 
    metadata: 
      labels:
        app: redis
        role: slave
        tier: backend
    spec: 
      containers:
      - name: slave
        image: gcr.io/google_samples/bg-redisslave:v1 # Imagem específica
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 6379
