apiVersion: v1
kind: Service
metadata: 
  name: redis-master # Nome do Serviço
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: 6379 # Porta Exposta no service
    targetPort: 6379 # Posta interna do conteiners
  selector: 
    app: redis
    role: master
    tier: backend
