apiVersion: v1
kind: Service
metadata: 
  name: service-example
  labels:
    app: apache-server
spec:
  ports:
    - port: 80
  selector:    
    app: apache-server
    tier: front
  type: LoadBalancer

