apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example-local
  labels: 
    type: local
spec: 
  storageClassName: local-storage
  local: 
    path: /mnt/dados
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - example-node
